import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>
          <h1>Navbar</h1>
          <div className="h-[calc(100vh)-5rem] text-gray-800 container mx-auto">{children}</div>
        </main>
      </body>
    </html>
  );
}
