import Navbar from "@/components/Navbar";
import "./globals.css";
import Providers from "./providers";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body>
        <Providers>
          <main>
            <Navbar />
            <div className="h-[calc(100vh)-5rem] container mx-auto">
              {children}
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
